// CMS.UI/src/views/frontend/Team.vue
<template>
  <main id="main">
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Ekibimiz</h2>
          <ol>
            <li><router-link to="/">Anasayfa</router-link></li>
            <li>Ekibimiz</li>
          </ol>
        </div>
      </div>
    </section>

    <section id="team" class="team section-bg">
      <div class="container">
        <div class="row">
          <div
            class="col-lg-3 col-md-6 d-flex align-items-stretch"
            v-for="item in list"
            :key="item.id"
          >
            <div class="member">
              <div class="member-img">
                <img :src="item.imageUrl" class="img-fluid" alt="" />
                <div class="social">
                  <a target="_blank" :href="item.twitterUrl"
                    ><i class="pi pi-twitter"></i
                  ></a>
                  <a target="_blank" :href="item.facebookUrl"
                    ><i class="pi pi-facebook"></i
                  ></a>
                  <a target="_blank" :href="item.instagramUrl"
                    ><i class="pi pi-instagram"></i
                  ></a>
                  <a target="_blank" :href="item.linkedinUrl"
                    ><i class="pi pi-linkedin"></i
                  ></a>
                </div>
              </div>
              <div class="member-info">
                <h4>{{ item.name }} {{ item.surname }}</h4>
                <span
                  ><i class="pi pi-envelope"></i> {{ item.emailAddress }}</span
                >
                <span><i class="pi pi-phone"></i> {{ item.phone }}</span>
                <span>{{ item.title }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>

<script>
import { Endpoints } from "../../services/Endpoints";
import GlobalService from "../../services/GlobalService";

export default {
  data() {
    return {
      list: [],
    };
  },
  created() {
    this.getAll();
  },
  methods: {
    getAll() {
      GlobalService.Get(Endpoints.Team).then((res) => {
        this.list = res.data;
      });
    },
  },
};
</script>

<style>
</style>

// src/CMS.UI/src/app/frontend/team/team.component.ts
import { Component, OnInit } from '@angular/core';
import { SharedModule } from '../../shared.module';
import { AppService } from '../../services/app.service';
import { environment } from '../../../environments/environment';

@Component({
    selector: 'app-team',
    imports: [SharedModule],
    templateUrl: './team.component.html',
    styleUrl: './team.component.css'
})
export class TeamComponent implements OnInit {
  teams: any = [];
  total: number = 0;
  skip: number = 0;
  pageSize: number = 8;
  environment = environment;

  constructor(private appService: AppService) {}

  ngOnInit() {
    this.getTeams();
  }

  getTeams() {
    this.appService
      .post('Team/GetAllActive', {
        skip: this.skip,
        pageSize: this.pageSize,
      })
      .subscribe((res: any) => {
        this.teams = res.list;
        this.total = res.total;
      });
  }

  onPageChange(event: any) {
    this.skip = event.first;
    this.pageSize = event.rows;
    this.getTeams();
  }
}

<main class="main">
  <div class="page-title accent-background">
    <div class="container d-lg-flex justify-content-between align-items-center">
      <h1 class="mb-2 mb-lg-0">Teams</h1>
      <nav class="breadcrumbs">
        <ol>
          <li><a routerLink="/">Home</a></li>
          <li class="current">Teams</li>
        </ol>
      </nav>
    </div>
  </div>

  <section id="team" class="team section">
    <div class="container">
      <div class="row gy-4 mb-4">
        <div
          class="col-lg-3 col-md-6 d-flex align-items-stretch"
          *ngFor="let item of teams"
        >
          <div class="team-member">
            <div class="member-img">
              <img
                src="{{ environment.host }}{{ item.imageUrl }}"
                class="img-fluid"
                alt=""
              />
              <div class="social">
                <a target="_blank" href="{{ item.twitterUrl }}"
                  ><i class="pi pi-twitter"></i
                ></a>
                <a target="_blank" href="{{ item.facebookUrl }}"
                  ><i class="pi pi-facebook"></i
                ></a>
                <a target="_blank" href="{{ item.instagramUrl }}"
                  ><i class="pi pi-instagram"></i
                ></a>
                <a target="_blank" href="{{ item.linkedinUrl }}"
                  ><i class="pi pi-linkedin"></i
                ></a>
              </div>
            </div>
            <div class="member-info">
              <h4>{{ item.name }} {{ item.surname }}</h4>
              <span>{{ item.title }}</span>
            </div>
          </div>
        </div>
      </div>

      <div class="my-3 pg">
        <p-paginator
          appendTo="body"
          (onPageChange)="onPageChange($event)"
          [first]="skip"
          [rows]="pageSize"
          [totalRecords]="total"
          [rowsPerPageOptions]="[8, 16, 24]"
        />
      </div>
    </div>
  </section>
</main>
