// src/CMS.UI/src/app/frontend/blog/blog-category/blog-category.component.ts
import { Component, OnInit } from '@angular/core';
import { SharedModule } from '../../../shared.module';
import { AppService } from '../../../services/app.service';
import { environment } from '../../../../environments/environment';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-blog-category',
  templateUrl: './blog-category.component.html',
  styleUrls: ['./blog-category.component.scss'],
  imports: [SharedModule],
})
export class FE_BlogCategoryComponent implements OnInit {
  blogs: any = [];
  blogCategory: any;
  mostReads: any = [];
  blogCategories: any = [];
  total: number = 0;
  skip: number = 0;
  pageSize: number = 4;
  environment = environment;
  url = '';

  constructor(private appService: AppService, private router: ActivatedRoute) {}

  ngOnInit(): void {
    this.router.params.subscribe((params) => {
      this.url = params['url'];
      this.getBlogs();
      this.getByUrl();
    });
    this.getMostRead();
    this.getBlogCategories();
  }

  getBlogs() {
    this.appService
      .get(`Blog/GetBlogsByCategoryUrl/${this.url}?$count=true`)
      .subscribe((res: any) => {
        this.blogs = res.data;
        this.total = res.total;
      });
  }

  getByUrl() {
    this.appService.get(`BlogCategory/GetByUrl/${this.url}`).subscribe((res: any) => {
      this.blogCategory = res;
    });
  }

  getMostRead() {
    this.appService.get('Blog/MostRead').subscribe((res: any) => {
      this.mostReads = res;
    });
  }

  getBlogCategories() {
    this.appService.get('BlogCategory/GetAllWithCount').subscribe((res: any) => {
      this.blogCategories = res;
    });
  }

  onPageChange(event: any) {
    this.skip = event.first;
    this.pageSize = event.rows;
    this.getBlogs();
  }
}

<main class="main">
  <div class="page-title accent-background">
    <div class="container d-lg-flex justify-content-between align-items-center">
      <h1 class="mb-2 mb-lg-0">Blogs / {{blogCategory?.name}}</h1>
      <nav class="breadcrumbs">
        <ol>
          <li><a routerLink="/">Home</a></li>
          <li><a routerLink="/blog">Blog</a></li>
          <li class="current">{{blogCategory?.name}}</li>
        </ol>
      </nav>
    </div>
  </div>
  <section id="blog-posts" class="blog-posts section">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-6 mb-3" *ngFor="let blog of blogs">
              <article
                class="position-relative h-100 cursor-pointer"
                routerLink="../../blog/{{ blog.url }}/{{ blog.id }}"
              >
                <div class="post-img position-relative overflow-hidden">
                  <img
                    src="{{ environment.host }}{{ blog.imageUrl }}"
                    class="img-fluid"
                    alt=""
                  />
                  <span class="post-date">{{
                    blog.insertedDate | date : "dd.MM.yyyy"
                  }}</span>
                </div>

                <div class="post-content d-flex flex-column">
                  <h3 class="post-title">
                    {{ blog.title }}
                  </h3>

                  <div class="meta d-flex align-items-center mt-1">
                    <div class="d-flex align-items-center">
                      <i class="pi pi-user"></i>
                      <span class="ps-1">{{ blog.userName }}</span>
                    </div>
                    <div class="d-flex align-items-center ms-3">
                      <i class="pi pi-comments"></i>
                      <span class="ps-1">{{ blog.commentCount }}</span>
                    </div>
                  </div>
                  <p>
                    {{ blog.description }}
                  </p>
                </div>
              </article>
            </div>
          </div>

          <p-paginator
            (onPageChange)="onPageChange($event)"
            [first]="skip"
            [rows]="pageSize"
            [totalRecords]="total"
            [rowsPerPageOptions]="[4, 12, 20]"
          />
        </div>
        <div class="col-md-4" *ngIf="mostReads.length > 0">
          <div class="widgets-container m-0">
            <div class="search-widget mb-4">
              <form action="">
                <input type="text" />
                <button type="submit" title="Search">
                  <i class="pi pi-search"></i>
                </button>
              </form>
            </div>
            <h5 class="border-bottom border-2 pb-2">
              <i class="pi pi-list"></i> Blog Categories
            </h5>
            <div class="pb-4 pt-3">
              <div class="mb-3" *ngFor="let item of blogCategories">
                <a class="text-dark" routerLink="../../blog/{{ item.url }}">
                  <i class="pi pi-arrow-right pe-2"></i> {{ item.name }} ({{
                    item.blogCount
                  }})</a
                >
              </div>
            </div>
            <div class="">
              <h5 class="border-bottom border-2 pb-2 mb-3">Most Reads</h5>
              <div class="mb-4" *ngFor="let blog of mostReads">
                <div
                  class="card border-0 mb-4 cursor-pointer"
                  routerLink="../blog/{{ blog.url }}/{{ blog.id }}"
                >
                  <img
                    class="card-img-top"
                    src="{{ environment.host }}{{ blog.imageUrl }}"
                  />
                  <div class="fw-semibold mt-1 text-sm-start">
                    {{ blog.title }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

// CMS.UI/src/views/frontend/BlogCategory.vue
<template>
  <main id="main">
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog / {{blogCategory.name}}</h2>
          <ol>
            <li><router-link to="/">Anasayfa</router-link></li>
            <li><router-link to="/blog">Blog</router-link></li>
            <li>{{blogCategory.name}}</li>
          </ol>
        </div>
      </div>
    </section>

    <section id="blog" class="blog">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 entries">
            <DataView :value="blogCategory.blogs" layout="grid" :paginator="true" :rows="5">
              <template #grid="slotProps">
                <article class="entry">
                  <div class="entry-img">
                    <router-link
                      :to="`/blog/${slotProps.data.url}/${slotProps.data.id}`"
                    >
                      <img
                        :src="slotProps.data.imageUrl"
                        alt=""
                        class="img-fluid"
                      />
                    </router-link>
                  </div>

                  <h2 class="entry-title">
                    <router-link
                      :to="`/blog/${slotProps.data.url}/${slotProps.data.id}`"
                    >
                      {{ slotProps.data.title }}
                    </router-link>
                  </h2>

                  <div class="entry-meta">
                    <ul>
                      <li class="d-flex align-items-center">
                        <i class="pi pi-user"></i>
                        {{ slotProps.data.userName }}
                      </li>
                      <li class="d-flex align-items-center">
                        <i class="pi pi-clock"></i>
                        <time>
                          {{ dateFormatValue(slotProps.data.insertedDate) }}
                        </time>
                      </li>
                      <li class="d-flex align-items-center">
                        <i class="pi pi-comments"></i>
                        {{ slotProps.data.commentCount }} Yorum
                      </li>
                    </ul>
                  </div>

                  <div class="entry-content">
                    <p>
                      {{ slotProps.data.description }}
                    </p>
                    <div class="read-more">
                      <router-link
                        :to="`/blog/${slotProps.data.url}/${slotProps.data.id}`"
                        >Daha Fazlası &nbsp;
                        <i class="pi pi-arrow-circle-right"></i
                      ></router-link>
                    </div>
                  </div>
                </article>
              </template>
              <template #empty
                ><p class="my-3 alert alert-info">Kayıt bulunamadı.</p>
              </template>
            </DataView>
          </div>
          <div class="col-lg-4">
            <div class="sidebar border">
              <h3 class="sidebar-title">Ara</h3>
              <div class="sidebar-item search-form">
                <div class="p-inputgroup">
                  <InputText placeholder="Ara" v-model="searchText" />
                  <Button
                    icon="pi pi-search"
                    class="bg-green"
                    @click="search()"
                  />
                </div>
              </div>
              <h3 class="sidebar-title">Kategoriler</h3>
              <div class="sidebar-item categories">
                <ul>
                  <li
                    class="py-2"
                    v-for="item in blogCategories"
                    :key="item.id"
                  >
                    <router-link :to="`/blog/${item.url}`"
                      >{{ item.name }}
                      <span>({{ item.blogCount }})</span></router-link
                    >
                  </li>
                </ul>
              </div>
              <h3 class="sidebar-title">Çok Okunanlar</h3>
              <div class="sidebar-item recent-posts">
                <div
                  class="post-item clearfix py-2"
                  v-for="item in mostReadList"
                  :key="item.id"
                >
                  <router-link :to="`/blog/${item.url}/${item.id}`">
                    <img :src="item.imageUrl" alt="" />
                  </router-link>
                  <h4>
                    <router-link :to="`/blog/${item.url}/${item.id}`">{{
                      item.title
                    }}</router-link>
                  </h4>
                  <time> {{ dateFormatValue(item.insertedDate) }}</time>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>

<script>
import { Endpoints } from "../../services/Endpoints";
import GlobalService from "../../services/GlobalService";
import dateFormat from "../../infrastructure/DateFormat";

export default {
  data() {
    return {
      title: "",
      loading: true,
      blogCategory: {},
      blogCategories: [],
      mostReadList: [],
      searchText: null,
      visibleError: false,
      message: "",
    };
  },
  created() {
    this.getAll();
    this.getBlogCategories();
    this.mostRead();
  },
  methods: {
    getAll() {
      var url = this.$route.params.categoryUrl;
      GlobalService.Get(`${Endpoints.Blog}/GetBlogsByCategoryUrl/${url}`)
        .then((res) => {
          this.blogCategory = res.data;
          this.loading = false;
        })
        .catch((e) => {
          this.visibleError = true;
          this.message = e.response.data.message;
        });
    },
    getBlogCategories() {
      GlobalService.Get(Endpoints.BlogCategory).then((res) => {
        this.blogCategories = res.data;
      });
    },
    dateFormatValue(value) {
      return dateFormat.convertShortDate(value);
    },
    mostRead() {
      var url = this.$route.params.categoryUrl;
      GlobalService.Get(`${Endpoints.Blog}/MostReadByBlogCategory/${url}`).then(
        (res) => {
          this.mostReadList = res.data;
        }
      );
    },
    search() {
      if (this.searchText) {
        this.$router.push(`/blog?ara=${this.searchText}`);
      } else {
        this.$router.push("/blog");
      }
    },
  },
};
</script>
