// src/CMS.UI/src/app/frontend/contact/contact.component.ts
import { AppService } from './../../services/app.service';
import { Component, OnInit } from '@angular/core';
import { SharedModule } from '../../shared.module';
import {
  AbstractControl,
  FormBuilder,
  FormGroup,
  Validators,
} from '@angular/forms';

@Component({
  selector: 'app-contact',
  imports: [SharedModule],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css',
})
export class FE_ContactComponent implements OnInit {
  contactCategories: any = [];
  submitted = false;
  form: FormGroup = this.formBuilder.group({
    name: [null, Validators.required],
    surname: [null, Validators.required],
    emailAddress: [null, [Validators.required, Validators.email]],
    contactCategoryId: [null, Validators.required],
    message: [null, Validators.required],
  });

  constructor(
    private appService: AppService,
    private formBuilder: FormBuilder
  ) {}

  ngOnInit(): void {
    this.getContactCategories();
  }

  get f(): { [key: string]: AbstractControl } {
    return this.form.controls;
  }

  getContactCategories() {
    this.appService.get('Lookup/ContactCategories').subscribe((res: any) => {
      this.contactCategories = res;
    });
  }

  save() {
    this.submitted = true;
    if (this.form?.invalid) {
      return;
    }
    this.appService
      .post(`Contact/Create`, this.form.value)
      .subscribe((res: any) => {
        this.form.reset();
        this.submitted = false;
        this.form.clearAsyncValidators();
      });
  }
}

<main class="main">
  <div class="page-title accent-background">
    <div class="container d-lg-flex justify-content-between align-items-center">
      <h1 class="mb-2 mb-lg-0">Contact</h1>
      <nav class="breadcrumbs">
        <ol>
          <li><a routerLink="/">Home</a></li>
          <li class="current">Contact</li>
        </ol>
      </nav>
    </div>
  </div>

  <section id="contact" class="contact section" style="padding: 60px 0">
    <div class="container">
      <div class="row gy-5 gx-lg-5">
        <div class="col-lg-4">
          <div class="info">
            <h3>Get in touch</h3>
            <p>
              Et id eius voluptates atque nihil voluptatem enim in tempore
              minima sit ad mollitia commodi minus.
            </p>

            <div class="info-item d-flex">
              <i class="bi bi-geo-alt flex-shrink-0"></i>
              <div>
                <h4>Location:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>
            </div>

            <div class="info-item d-flex">
              <i class="bi bi-envelope flex-shrink-0"></i>
              <div>
                <h4>Email:</h4>
                <p>info&#64;example.com</p>
              </div>
            </div>

            <div class="info-item d-flex">
              <i class="bi bi-phone flex-shrink-0"></i>
              <div>
                <h4>Call:</h4>
                <p>+1 5589 55488 55</p>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-8">
          <div class="info">
            <h4 class="mb-3">Your Message</h4>
            <form [formGroup]="form">
              <div class="row">
                <div class="col-md-6 mb-4">
                  <input
                    type="text"
                    pInputText
                    class="w-100"
                    placeholder="Your Name"
                    formControlName="name"
                    [ngClass]="{
                      'is-invalid': submitted && f['name'].errors
                    }"
                  />
                  <div
                    *ngIf="submitted && f['name'].errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="f['name'].errors['required']">
                      Name is required
                    </div>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <input
                    class="w-100"
                    type="text"
                    pInputText
                    placeholder="Your Surname"
                    formControlName="surname"
                    [ngClass]="{
                      'is-invalid': submitted && f['surname'].errors
                    }"
                  />
                  <div
                    *ngIf="submitted && f['surname'].errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="f['surname'].errors['required']">
                      Surname is required
                    </div>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <input
                    class="w-100"
                    type="text"
                    pInputText
                    placeholder="Your Email"
                    formControlName="emailAddress"
                    [ngClass]="{
                      'is-invalid': submitted && f['emailAddress'].errors
                    }"
                  />
                  <div
                    *ngIf="submitted && f['emailAddress'].errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="f['emailAddress'].errors['required']">
                      Email address is required
                    </div>
                    <div *ngIf="f['emailAddress'].errors['email']">
                      Email address invalid format
                    </div>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <p-select
                    placeholder="Select category"
                    styleClass="w-100"
                    [options]="contactCategories"
                    optionLabel="name"
                    optionValue="id"
                    [filter]="true"
                    formControlName="contactCategoryId"
                    [ngClass]="{
                      'is-invalid': submitted && f['contactCategoryId'].errors
                    }"
                  />
                  <div
                    *ngIf="submitted && f['contactCategoryId'].errors"
                    class="invalid-feedback"
                  >
                    <div *ngIf="f['contactCategoryId'].errors['required']">
                      Category is required
                    </div>
                  </div>
                </div>
              </div>
              <div class="mb-4">
                <textarea
                  rows="5"
                  cols="30"
                  class="w-100"
                  pTextarea
                  placeholder="Message"
                  formControlName="message"
                  [ngClass]="{
                    'is-invalid': submitted && f['message'].errors
                  }"
                ></textarea>
                <div
                  *ngIf="submitted && f['message'].errors"
                  class="invalid-feedback"
                >
                  <div *ngIf="f['message'].errors['required']">
                    Message is required
                  </div>
                </div>
              </div>
              <div class="">
                <p-button
                  class="float-end"
                  icon="pi pi-send"
                  label="Send"
                  (click)="save()"
                  type="submit"
                  severity="warn"
                  pAutoFocus
                  [autofocus]="true"
                ></p-button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

// CMS.UI/src/views/frontend/Contact.vue
<template>
  <main id="main">
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>İletişim</h2>
          <ol>
            <li><router-link to="/">Anasayfa</router-link></li>
            <li>İletişim</li>
          </ol>
        </div>
      </div>
    </section>

    <div class="map-section">
      <iframe
        style="border: 0; width: 100%; height: 350px"
        src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
        frameborder="0"
        allowfullscreen
      ></iframe>
    </div>

    <section id="contact" class="contact">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-10">
            <div class="info-wrap bg-white">
              <div class="row">
                <div class="col-lg-4 info">
                  <i class="pi pi-map-marker"></i>
                  <h4>Location:</h4>
                  <p>A108 Adam Street<br />New York, NY 535022</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="pi pi-envelope"></i>
                  <h4>Email:</h4>
                  <p>info@example.com<br />contact@example.com</p>
                </div>

                <div class="col-lg-4 info mt-4 mt-lg-0">
                  <i class="pi pi-phone"></i>
                  <h4>Call:</h4>
                  <p>+1 5589 55488 51<br />+1 5589 22475 14</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row mt-5 justify-content-center">
          <div class="col-lg-10">
            <div class="contact-form">
              <div class="row py-3">
                <div class="col-md-6 offset-3">
                  <div class="mb-3">
                    <label class="form-label fw-bold">Konusu</label>
                    <Dropdown
                      class="w-100"
                      v-model="data.contactCategoryId"
                      :options="contactCategories"
                      optionLabel="name"
                      optionValue="id"
                      placeholder="Konu seçiniz."
                    />
                  </div>
                  <div class="mb-3">
                    <label class="form-label fw-bold">Adı</label>
                    <InputText class="w-100" type="text" v-model="data.name" />
                  </div>
                  <div class="mb-3">
                    <label class="form-label fw-bold">Soyadı</label>
                    <InputText
                      class="w-100"
                      type="text"
                      v-model="data.surname"
                    />
                  </div>
                  <div class="mb-3">
                    <label class="form-label fw-bold">Email Adresi</label>
                    <InputText
                      class="w-100"
                      type="email"
                      v-model="data.emailAddress"
                    />
                  </div>
                  <div class="mb-3">
                    <label class="form-label fw-bold">Mesajı</label>
                    <Textarea
                      class="w-100"
                      v-model="data.message"
                      rows="5"
                    ></Textarea>
                  </div>
                  <div class="mb-3">
                    <Button type="submit" label="Gönder" @click="save"></Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Contact Section -->
  </main>
</template>

<script>
import AlertService from "../../services/AlertService";
import { Endpoints } from "../../services/Endpoints";
import GlobalService from "../../services/GlobalService";
export default {
  mixins: [AlertService],
  data() {
    return {
      contactCategories: [],
      data: {
        contactCategoryId: 0,
        name: "",
        surname: "",
        emailAddress: "",
        message: "",
      },
    };
  },
  created() {
    GlobalService.Get(Endpoints.Lookup.ContactCategories).then((res) => {
      this.contactCategories = res.data;
    });
  },
  methods: {
    save() {
      GlobalService.Post(Endpoints.Contact, this.data)
        .then(() => {
          this.data = {};
          this.successMessage(
            this,
            "Mesajınız başarıyla kaydedildi. En kısa zamanda dönüş sağlanacaktır."
          );
        })
        .catch((e) => {
          this.errorMessage(e.response.data.message);
        });
    },
  },
};
</script>
