// src/CMS.UI/src/app/frontend/testimonial/testimonial.component.ts
import { environment } from '../../../environments/environment';
import { SharedModule } from '../../shared.module';
import { AppService } from './../../services/app.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testimonial',
  imports: [SharedModule],
  templateUrl: './testimonial.component.html',
  styleUrl: './testimonial.component.css',
})
export class FE_TestimonialComponent implements OnInit {
  list: any = [];
  total = 0;
  first: number = 0;
  rows: number = 4;

  environment = environment;

  constructor(private appService: AppService) {}

  ngOnInit() {
    this.getList();
  }

  getList() {
    this.appService
      .get(`Testimonial/Get?$skip=${this.first}&$top=${this.rows}&$count=true`)
      .subscribe((res: any) => {
        this.list = res.data;
        this.total = res.total;
      });
  }

  onPageChange(e: any) {
    this.first = e.first;
    this.rows = e.rows;
    this.getList();
  }
}

<main class="main">
  <div class="page-title accent-background">
    <div class="container d-lg-flex justify-content-between align-items-center">
      <h1 class="mb-2 mb-lg-0">Testimonials</h1>
      <nav class="breadcrumbs">
        <ol>
          <li><a routerLink="/">Home</a></li>
          <li class="current">Testimonials</li>
        </ol>
      </nav>
    </div>
  </div>

  <section id="testimonials" class="testimonials section">
    <div class="container">
      <div class="row gy-4">
        <div class="col-md-6" *ngFor="let item of list">
          <div class="testimonial-item">
            <img
            src="{{ environment.host }}{{ item.imageUrl }}"
            class="testimonial-img"
              alt=""
            />
            <h3>{{ item.name }} {{ item.surname }}</h3>
            <h4>{{ item.title }}</h4>
            <p class="mt-5">
              <i class="bi bi-quote quote-icon-left"></i>
              <span [innerHTML]="item.description"></span>
              <i class="bi bi-quote quote-icon-right"></i>
            </p>
          </div>
        </div>
      </div>
      <div class="mt-3">
        <p-paginator
          (onPageChange)="onPageChange($event)"
          [first]="first"
          [rows]="rows"
          [totalRecords]="total"
          [rowsPerPageOptions]="[4, 12, 20]"
        />
      </div>
    </div>
  </section>
</main>

// CMS.UI/src/views/frontend/Testimonial.vue
<template>
  <main id="main">
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Referanslar</h2>
          <ol>
            <li><router-link to="/">Anasayfa</router-link></li>
            <li>Referanslar</li>
          </ol>
        </div>
      </div>
    </section>

    <section id="testimonials" class="testimonials section-bg">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-3" v-for="item in list" :key="item.id">
            <div class="testimonial-item">
              <img :src="item.imageUrl" class="testimonial-img" />
              <h3>{{ item.name }} {{ item.surname }}</h3>
              <h4><span v-if="item.corporateName">{{ item.corporateName }} / </span>{{ item.title }}</h4>
              <p v-html="item.description"></p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</template>

<script>
import { Endpoints } from "../../services/Endpoints";
import GlobalService from "../../services/GlobalService";

export default {
  data() {
    return {
      list: [],
    };
  },
  created() {
    this.getAll();
  },
  methods: {
    getAll() {
      GlobalService.Get(Endpoints.Testimonial).then((res) => {
        this.list = res.data;
      });
    },
  },
};
</script>

<style>
</style>
